# Site settings
title: Alpha Olomi
description: Personal & Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://alphaolomi.me" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Alpha Olomi
user_description: I\'m a nomad Software Engineer, always searching for the next challenge; no task is too scary nor too difficult. Lately I have been immersed in <b>freelancing</b> , trying to create the next Facebook..
user_title: Software Engineer
email: alphaolomi@gmail.com
twitter_username: alphaolomi
github_username:  alphaolomi
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
